### ISSUE TITLE
convert_to_discrete() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by Daraan** [CORE-Robotics-Lab/Interpretable_DDTS_AISTATS2020#3]
Hello, I am trying to run your code, however there is one change that confused me. In one of your updates you added a second argument to `convert_to_discrete`.

https://github.com/CORE-Robotics-Lab/Interpretable_DDTS_AISTATS2020/blob/a7fde4d2a7d70477b2e6c96b140f8c6587f78791/interpretable_ddts/runfiles/run_discrete_agent.py#L52

However the current code of `convert_to_discrete` does only accept one keyword.

https://github.com/CORE-Robotics-Lab/Interpretable_DDTS_AISTATS2020/blob/a7fde4d2a7d70477b2e6c96b140f8c6587f78791/interpretable_ddts/opt_helpers/discretization.py#L7

Is there perhaps an update that you haven't uploaded yet?

**Comment by andrewsilva9** [comment]
Hello and thanks for catching this! It looks like the solution you've linked (accepting a parameter and not using it, or just deleting the second parameter as input) would work fine. I don't think it is supposed to be used for anything. 

Unfortunately this code is no longer being actively maintained, and I can't look into this too much right now. But let me know if you have further issues and I can do my best to help out from memory!

**Comment by Daraan** [comment]
Thank you very much for the reply and I fully understand :)

---

One more question, do you have the wildfire code still available would you be willing to share it (privately)?

**Comment by andrewsilva9** [comment]
Thanks for the fixes, I will take a look at/merge that PR!

Unfortunately I do not have the original code or wildfire game anymore, but the author of that original game went on to develop a fully fledged python game that he used frequently in his research, which you can find here:
https://github.com/EsiSeraj/FireCommander2020 (the repo has links to the original papers and to other repos which use that wildfire domain for RL).
